<?php
$wp_ffpc_config = array (
  'dulichkhampha.net' => 
  array (
    'hosts' => '127.0.0.1:11211',
    'memcached_binary' => 0,
    'authpass' => '123456huy',
    'authuser' => 'admin',
    'browsercache' => 0,
    'browsercache_home' => 0,
    'browsercache_taxonomy' => 0,
    'expire' => '3600',
    'expire_home' => '3600',
    'expire_taxonomy' => '3600',
    'invalidation_method' => '1',
    'prefix_meta' => 'meta-',
    'prefix_data' => 'data-',
    'charset' => 'utf-8',
    'log' => 0,
    'cache_type' => 'memcached',
    'cache_loggedin' => 0,
    'nocache_home' => 0,
    'nocache_feed' => 0,
    'nocache_archive' => 0,
    'nocache_single' => 0,
    'nocache_page' => 0,
    'nocache_cookies' => 0,
    'nocache_dyn' => '1',
    'nocache_woocommerce' => '1',
    'nocache_woocommerce_url' => '',
    'nocache_url' => '^/wp-',
    'nocache_comment' => '',
    'response_header' => 0,
    'generate_time' => 0,
    'precache_schedule' => 'daily',
    'key' => '$scheme://$host$request_uri',
    'comments_invalidate' => '1',
    'pingback_header' => 0,
    'hashkey' => 0,
    'version' => '1.11.2',
  ),
);
include_once ('/var/www/dulichkhampha.net/wp-dlkp/wp-content/plugins/wp-ffpc/wp-ffpc-acache.php');